# Generated by Django 3.0.6 on 2020-05-14 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_auto_20200514_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejemplar',
            name='usuarioActual',
        ),
    ]
